---
title: "CA Election 2022 Data Challenge"
author: "GitData"
date: "10/12/2022"
output:
  html_document:
    toc: yes
    toc_depth: '5'
    df_print: paged
  pdf_document:
    toc: yes
    toc_depth: 5
---

\clearpage
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(knitr)
library(ggplot2)
library(dplyr)
library(GGally)
library(lmtest)
library(car)
```

# I. Introduction and Research Questions

// Type your solution here

# II. Data Information
```{r, include=FALSE}
################################################
##########II. Data Information##################
################################################
# Load dataset
pollution = read.csv("https://caelection2022.gitdata.ga/dataset/EMFAC2021-EI-202x.csv", 
                     header = TRUE)
income = read.csv("https://caelection2022.gitdata.ga/dataset/2020_Combined_AR_PIT_B4A.csv", 
                    header = TRUE)
fuelStation = read.csv("https://caelection2022.gitdata.ga/dataset/alt_fuel_stations.csv",
                       header = TRUE)
carSale = read.csv("https://caelection2022.gitdata.ga/dataset/New_ZEV_Sales_County.csv", 
                    header = TRUE)
# Improve the pollution data by calculating the mean of each pollutant by county
pollutionAVG = pollution %>% group_by(Region) %>%
                mutate(CO2_AVG = mean(CO2_RUNEX),
                       CH4_AVG = mean(CH4_RUNEX),
                       N2O_AVG = mean(N2O_RUNEX),
                       GHG_AVG = mean(CO2_RUNEX + CH4_RUNEX + N2O_RUNEX))
```


# III. Data Visualization
```{r}
################################################
##########III. Data Visualization###############
################################################
# Linear regression for CO2
co2.model.avg = lm(CO2_AVG ~ Total.VMT + as.character(Fuel) + 
                       as.character(Model.Year) + as.character(Region) +
                       as.character(Speed), data = pollutionAVG)
par(mfrow = c(2, 2))
plot(co2.model.avg)
summary(co2.model.avg)
# Multicollinearity (no issue)
vif(co2.model.avg)
# Constant variance test (no issue)
bptest = bptest(co2.model.avg)
bptest
```

```{r}
# Linear regression for CH4
ch4.model.avg = lm(CH4_AVG ~ Total.VMT + as.character(Fuel) + 
                       as.character(Model.Year) + as.character(Region) +
                       as.character(Speed), data = pollutionAVG)
par(mfrow = c(2, 2))
plot(ch4.model.avg)
summary(ch4.model.avg)
# Multicollinearity (no issue)
vif(ch4.model.avg)
# Constant variance test (no issue)
bptest = bptest(ch4.model.avg)
bptest
```

```{r}
# Linear regression for N2O
n2o.model.avg = lm(N2O_AVG ~ Total.VMT + as.character(Fuel) + 
                       as.character(Model.Year) + as.character(Region) +
                       as.character(Speed), data = pollutionAVG)
par(mfrow = c(2, 2))
plot(n2o.model.avg)
summary(n2o.model.avg)
# Multicollinearity (no issue)
vif(n2o.model.avg)
# Constant variance test (p-value = 0.04228 around the rejection region)
bptest = bptest(n2o.model.avg)
bptest
```

```{r}
# Linear regression for GHG
ghg.model.avg = lm(GHG_AVG ~ Total.VMT + as.character(Fuel) + 
                       as.character(Model.Year) + as.character(Region) +
                       as.character(Speed), data = pollutionAVG)
par(mfrow = c(2, 2))
plot(ghg.model.avg)
summary(ghg.model.avg)
# Multicollinearity (no issue)
vif(ghg.model.avg)
# Constant variance test (no issue)
bptest = bptest(ghg.model.avg)
bptest
```


# IV. Analysis

// Type your solution here

# V. Result and Interpretation

// Type your solution here

# VI. Conclusion and Future Discussion

// Type your solution here


\clearpage

# Appendix: R Script

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```