---
title: "California Election 2022 Data Challenge"
author: "GitData"
date: "10/11/2022"
output:
  pdf_document:
    toc: yes
    toc_depth: 5
  html_document:
    toc: yes
    toc_depth: '5'
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list=ls())
library(knitr)
library(ggplot2)
library(dplyr)
```

```{r, echo=FALSE, WARNING = FALSE}
# Load the data
dataset1 = read.csv("https://caelection2022.gitdata.ga/dataset/EMFAC2021-EI-202xC.csv",
                    header = TRUE)
# View(dataset1)
kable(dataset1 %>% group_by(Region, Fuel) %>% summarize(NOx = round(NOx_TOTEX, 3), 
                                                        CO2 = round(CO2_TOTEX, 3),
                                                        CH4 = round(CH4_TOTEX, 3),
                                                        N2O = round(N2O_TOTEX, 3),
                                                        CO = round(CO_TOTEX, 3),
                                                        SOx = round(SOx_TOTEX, 3)))
```
